version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: sequencerDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
  web:
    image: php:7.2.2-apache
    container_name: php_web
    build: ./php_web
    depends_on:
      - db
    volumes: 
      - ./www/:/var/www/
    ports:
      - '8100:80'
    stdin_open: true
    tty: true